version: '3.8'
services:
  postgresdb:
    container_name: postgresdb
    image: postgres
    ports:
      - '6543:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 121212
      POSTGRES_DB: test_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-container
    ports:
      - '5000:5000'
    depends_on:
      - postgresdb
    restart: always

  pgadmin:
    container_name: container-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgresdb
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 121212
    restart: unless-stopped

volumes:
  postgres-data:
