version: '3.9'
services:
  postgresdb:
    container_name: container-pg
    image: postgres:17-alpine
    hostname: localhost
    ports:
      - '127.0.0.1:6543:5432'
    environment:
      PGUSER: postgres
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: container-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgresdb
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 121212
    restart: unless-stopped

volumes:
  postgres-data:
