version: '3.9'
services:
  postgresdb:
    container_name: container-pg
    image: postgres:17-alpine
    hostname: localhost
    ports:
      - '6543:5432'
    environment:
      PGUSER: ${PG_USER}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
