version: '3.8'
services:
  postgresdb:
    container_name: container-pg
    image: postgres
    hostname: localhost
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_DB: $PG_DB
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
