version: '3.9'
services:
  postgresdb:
    container_name: container-pg
    image: postgres:17-alpine
    hostname: localhost
    ports:
      - '6543:5432'
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 121212
      POSTGRES_DB: test_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
