version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-container
    ports:
      - '5000:5000'
    depends_on:
      - postgresdb
    restart: always

  postgresdb:
    container_name: pg-container
    image: postgres
    hostname: localhost
    ports:
      - '127.0.0.1:6543:5432'
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_DB: $PG_DB
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
